# Generated by Django 3.1.7 on 2021-03-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_auto_20210303_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='Message',
            field=models.TextField(),
        ),
    ]
